//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCommerce.Transactions.Payments.GiftCard.UI {
    
    
    public partial class EditGiftCardPrices {
        
        /// <summary>
        /// ValidationSummary1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UCommerce.Transactions.Payments.Giftcard.UI.ValidationSummaryDisplay ValidationSummary1;
        
        /// <summary>
        /// GiftCardPrices control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ucommerce.Presentation.Web.Controls.BulkEditGridView GiftCardPrices;
    }
}
